export const url = 'https://homeclixteste.dataclix.com.br:3312/'
export const apiKey = 'AKGYqUJzBDIXWXFZtxVBprRofZsRZHxlcamUMdEVKdczvQHseTupRmPjgXyApcRHEeetFVMroPpjxjcNTydMkSgTbdazGXJTVdoEqQDODYYNFNkwMPDgWRUFwApnxAJx'
export const accessTokenHomeclix = 'F3aN8XDCvMstYf'
export const refreshTokenHomeclix = 'PLSYNsSrVpa2uh'
export const lembrarHomeclix = 'feBa7Hz86DD9YK'
